name: flutter_login_register_ui
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+13

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  another_flushbar: ^1.10.22
  awesome_button: ^1.0.2
  bottom_loader: ^0.1.2
  change_app_package_name: ^1.0.0
  colour: ^1.0.4
  cool_stepper: ^1.1.3
  cupertino_icons: ^1.0.0
  cupertino_radio_choice: ^1.0.1+1
  date_time_picker: ^2.0.0
  double_back_to_close: ^2.0.0
  draggable_bottom_sheet: ^0.1.2
  fbutton: ^2.0.1
  flutter_awesome_alert_box: ^1.0.1
  flutter_custom_clippers: ^1.1.2
  flutter_datetime_picker: ^1.5.1
  flutter_html: ^1.2.0
  flutter_launcher_icons: ^0.8.1
  flutter_open_whatsapp: ^0.1.2
  flutter_screenutil: ^5.0.0+2
  flutter_secure_storage: ^4.1.0
  flutter_styled_toast: ^2.0.0
  flutter_svg_provider: ^0.1.8-nullsafety.0
  get: ^4.1.4
  hexcolor: ^2.0.3
  http: ^0.13.0
  http_parser: ^4.0.0
  image_picker: ^0.8.0
  in_app_update: ^2.0.0
  intl: ^0.17.0
  modal_progress_hud: ^0.1.3
  notus: ^0.1.5
  onesignal_flutter: ^2.6.3
  page_transition: ^1.1.7+6
  pk_skeleton: ^0.0.2
  pop_bottom_menu: ^1.0.0
  quill_delta: ^1.0.1
  shared_preferences: ^2.0.5
  simple_animations: ^1.3.3
  skeleton_text: ^3.0.0
  slider_button: ^0.6.0
  splash_screen_view: ^1.0.3
  steppers: ^0.0.1
  toast_badge: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/icon.png"
# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/images/
    - assets/images/barang/
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  # - family: MyFlutterApp
  #   fonts:
  #     - asset: fonts/NewsIcon.ttf
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
